name = "calculator example"

[target.pytest]
out_dir = "./generated/pytest"

[target.bun]
out_dir = "./generated/bun"

[suite.8bit]
groups = ["add", "multiply"]

[suite.16bit]
groups = ["add", "multiply"]

[group.add]
desc = "Addition tests"

[group.multiply]
desc = "Multiplication tests"

[test.sum]
group = "add"

[test.overflow_sum]
group = "add"

[test.product]
group = "multiply"

[test.product_overflow]
group = "multiply"

[target.custom_pytest]
out_dir = "./generated/custom_pytest"

suite_file_name_template = "test_{{ suite.name | convert_case('Snake') }}.py"
test_regex_template = "def test_{{ name | convert_case('Snake') }}\\("

template_dir = "./templates/custom_pytest"

[target.custom_pytest.runner]
fail_regex_template = "{{ file_name }}::test_{{ test_name }} FAILED"
pass_regex_template = "{{ file_name }}::test_{{ test_name }} PASSED"
command = "pytest"
args = ["-v"]
