name = "vehicles example"

[target.pytest]
out_dir = "./generated/pytest"

[target.markdown]
out_dir = "./generated"

[target.bun]
out_dir = "./generated/bun"

# Each suite, group, and test table must contain a unique identifier. These tables may also have:
# - name: a human readable name that will be used in the generated tests (i.e. the test name in jest)
# - desc: a description that will show up in the generated tests as a comment
#
# `name` and `desc` will also be used when generating the markdown file

# Suites are the top level of the test hierarchy and contain groups of tests
# Each suite typically maps to a new test file in the generated test directory
[suite.motorcycle]
groups = ["valid_vehicle", "invalid_vehicle", "broken_vehicle"]

[suite.car]
groups = ["valid_vehicle", "invalid_vehicle", "broken_vehicle"]

# Groups contain multiple tests

[group.valid_vehicle]
name = "valid vehicle"
tests = ["valid_headlights", "valid_tires"] # array of test ids
desc = "Functionality works as expected when the vehicle is valid and not missing any parts"

[group.invalid_vehicle]
name = "invalid vehicle"
tests = ["extra_headlight", "extra_tire"]
desc = "Errors are thrown when the vehicle has extra parts, which should never happen"

[group.broken_vehicle]
name = "broken vehicle"
tests = ["broken_headlight", "flat_tire"]
desc = "When the vehicle has parts that need repair, the respective functions should detect the issue"

# Tests define the actual tests that will be generated

[test.valid_headlights]
name = "check headlights"
desc = "The function for checking headlights should return true if the vehicle has the correct number of headlights"

[test.valid_tires]
name = "check tires"
desc = "The function for checking tires should return true if the vehicle has the correct number of inflated tires"

[test.broken_headlight]
name = "broken headlight is caught"
desc = "The function for checking headlights should return false if the vehicle has a broken headlight"

[test.flat_tire]
name = "flat tire is caught"
desc = "The function for checking tires should return false if the vehicle has a flat tire"

[test.extra_tire]
name = "extra tire throws error"
desc = "Having an extra tire is invalid and should throw an error"

[test.extra_headlight]
name = "extra headlight throws error"
desc = "Having an extra headlight is invalid and should throw an error"
