name = "vehicles example"

[target.pytest]
out_dir = "./generated/pytest"

[target.markdown]
out_dir = "./generated"

# Each suite, group, and test table must contain a unique identifier. These tables may also have:
# - name: a human readable name that will be used in the generated tests (i.e. the test name in jest)
# - desc: a description that will show up in the generated tests as a comment
#
# `name` and `desc` will also be used when generating the markdown file

# Suites are the top level of the test hierarchy and contain groups of tests
# Each suite typically maps to a new test file in the generated test directory
[[suite]]
id = "motorcycle"
groups = ["valid vehicle", "invalid vehicle", "broken vehicle"]

[[suite]]
id = "car"
groups = ["valid vehicle", "invalid vehicle", "broken vehicle"]

# Groups contain multiple tests

[[group]]
id = "valid vehicle"
tests = ["valid headlights", "valid tires"] # array of test ids
desc = "Functionality works as expected when the vehicle is valid and not missing any parts"

[[group]]
id = "invalid vehicle"
tests = ["extra headlight", "extra tire"]
desc = "Errors are thrown when the vehicle has extra parts, which should never happen"

[[group]]
id = "broken vehicle"
tests = ["broken headlight", "flat tire"]
desc = "When the vehicle has parts that need repair, the respective functions should detect the issue"

# Tests define the actual tests that will be generated

[[test]]
id = "valid headlights" 
name = "check headlights"
desc = "The function for checking headlights should return true if the vehicle has the correct number of headlights"

[[test]]
id = "valid tires"
name = "check tires"
desc = "The function for checking tires should return true if the vehicle has the correct number of inflated tires"

[[test]]
id = "broken headlight"
name = "broken headlight is caught"
desc = "The function for checking headlights should return false if the vehicle has a broken headlight"

[[test]]
id = "flat tire"
name = "flat tire is caught"
desc = "The function for checking tires should return false if the vehicle has a flat tire"

[[test]]
id = "extra tire"
name = "extra tire throws error"
desc = "Having an extra tire is invalid and should throw an error"

[[test]]
id = "extra headlight"
name = "extra headlight throws error"
desc = "Having an extra headlight is invalid and should throw an error"
