# The name of the test plan
name = "vehicles example"

# A target defines how the tests will be generated and validated
# Polytest includes some targets out of the box, in which case you just need to specify the output directory

# The pytest target will generate Python tests for pytest
[target.pytest]
out_dir = "./generated/pytest"

# The markdown target will generate a markdown file with the test plan
[target.markdown]
out_dir = "./generated"

# The bun target will generate TypeScript tests for the bun test runner
[target.bun]
out_dir = "./generated/bun"

# Each suite, group, and test are defined in a table with a unique identifier. 
# The identifier should be fairly short and easy to read/write within this file.
#
# These tables may also have the following fields:
# - name: a human readable name that will be used in the generated tests (i.e. the test name in jest)
# - desc: a description that will show up in the generated tests as a comment
#
# If a name is not provided, the identifier will be used as the name
# If a desc is not provided, it will be an empty string

# Suites are the top level of the test hierarchy and contain groups of tests
# Each suite typically maps to a new test file in the generated test directory
[suite.motorcycle]
groups = ["valid_vehicle", "invalid_vehicle", "broken_vehicle"]

[suite.car]
groups = ["valid_vehicle", "invalid_vehicle", "broken_vehicle"]

# Groups contain multiple tests

[group.valid_vehicle]
name = "valid vehicle"
desc = "Functionality works as expected when the vehicle is valid and not missing any parts"

[group.invalid_vehicle]
name = "invalid vehicle"
desc = "Errors are thrown when the vehicle has extra parts, which should never happen"

[group.broken_vehicle]
name = "broken vehicle"
desc = "When the vehicle has parts that need repair, the respective functions should detect the issue"

# Tests define the actual tests that will be generated

[test.valid_headlights]
name = "check headlights"
group = "valid_vehicle"
desc = "The function for checking headlights should return true if the vehicle has the correct number of headlights"

[test.valid_tires]
name = "check tires"
group = "valid_vehicle"
desc = "The function for checking tires should return true if the vehicle has the correct number of inflated tires"

[test.broken_headlight]
name = "broken headlight is caught"
group = "broken_vehicle"
desc = "The function for checking headlights should return false if the vehicle has a broken headlight"

[test.flat_tire]
name = "flat tire is caught"
group = "broken_vehicle"
desc = "The function for checking tires should return false if the vehicle has a flat tire"

[test.extra_tire]
name = "extra tire throws error"
group = "invalid_vehicle"
desc = "Having an extra tire is invalid and should throw an error"

[test.extra_headlight]
name = "extra headlight throws error"
group = "invalid_vehicle"
desc = "Having an extra headlight is invalid and should throw an error"
