name = "custom targets example"

# The default pytest target
[target.pytest]
out_dir = "./generated/pytest"

[runner.pytest]
command = "pytest"
args = ["-v"]

# A custom target must define either of the following sets of options:
# 
# For test generation targets, which may have multiple suite files that are updated each time `polytest generate` is ran:
# - out_dir
# - template_dir
# - test_regex_template
# - suite_file_name_template
#
# For a plan generation target, which will only have one generated file that is regenerated each time `polytest generate` is ran:
# - out_dir
# - template_dir
# - plan_file_name_template
#
# See the comments in [test.test_cases_csv] for an example of a plan generation target
# and the comments in [target.pytest_with_fixtures] for an example of a test generation target
#
# It is also possible to create a target that generates both test suite files and a plan file

# This is a custom target that generates a CSV file with all the test cases in the plan
[target.test_cases_csv]
out_dir = "./generated"

# A Jinja template string for the name of the file that is generated
plan_file_name_template = "{{ name | convert_case('Snake') }}_test_cases.csv"

# Path to a directory containing a Jinja template file that matches plan*
template_dir = "./templates/test_cases_csv"

[target.pytest_with_fixtures]
out_dir = "./generated/pytest_with_fixtures"

# A Jinja template string used to determine which test cases are already implemented
test_regex_template = "def test_{{ name | convert_case('Snake') }}"

# A Jinja template string for the name of the file that is generated for each suite
# Note that multiple suites could be in the same file if desired (i.e. making this "test_all_suites.py")
suite_file_name_template = "test_{{ suite.name | convert_case('Snake') }}.py"

# The path to a driectory containing the following files:
#
# suite*: a Jinja template file for the suite scaffloding
# MUST contain a comment with "Polytest Suite: {{ suite.name }}" somewhere in the template
# All of the group content will be generated under this comment
#
# group*: a Jinja template file for generating the group scaffolding
# MUST contain a comment with "Polytest Group: {{ group.name }}" somewhere in the template
# All of the test cases will be generated under this comment
#
# test*: a Jinja template file for generating the test case scaffolding
template_dir = "./templates/pytest_with_fixtures"


#########################################
# The suite, groups, and test definitions
#########################################

[suite.motorcycle]
groups = ["valid vehicle", "invalid vehicle", "broken vehicle"]

[suite.car]
groups = ["valid vehicle", "invalid vehicle", "broken vehicle"]

[group."valid vehicle"]
desc = "Functionality works as expected when the vehicle is valid and not missing any parts"

[group."invalid vehicle"]
desc = "Errors are thrown when the vehicle has extra parts, which should never happen"

[group."broken vehicle"]
desc = "When the vehicle has parts that need repair, the respective functions should detect the issue"

[test."check headlights"]
group = "valid vehicle"
desc = "The function for checking headlights should return true if the vehicle has the correct number of headlights"

[test."check tires"]
group = "valid vehicle"
desc = "The function for checking tires should return true if the vehicle has the correct number of inflated tires"

[test."broken headlight is caught"]
group = "broken vehicle"
desc = "The function for checking headlights should return false if the vehicle has a broken headlight"

[test."flat tire is caught"]
group = "broken vehicle"
desc = "The function for checking tires should return false if the vehicle has a flat tire"

[test."extra tire throws error"]
group = "invalid vehicle"
desc = "Having an extra tire is invalid and should throw an error"

[test."extra headlight throws error"]
group = "invalid vehicle"
desc = "Having an extra headlight is invalid and should throw an error"
